### ISSUE TITLE
AttributeError: 'PoseTrajectory3D' object has no attribute 'align'

### ISSUE THREAD

**Issue by wwtinwhu** [i2Nav-WHU/evaluate_odometry#1]
Hello, @thlsealight . I execute the evaluate_odo.py. I met the problem in the trajectory_align part as follows

`traj_est_aligned.align(traj_ref, correct_scale=False, correct_only_scale=False)`
I have installed evo and can use it in the command line. Do you have any advice ? Thanks!

**Comment by thlsealight** [comment]
Please refer to [evo commit](https://github.com/MichaelGrupp/evo/commit/e96d6a33415cd3a5fd25fefa4a6a69ee70e900e4), and make sure that the proper evo version is installed (1.16 for me).

**Comment by wwtinwhu** [comment]
> Please refer to [evo commit](https://github.com/MichaelGrupp/evo/commit/e96d6a33415cd3a5fd25fefa4a6a69ee70e900e4), and make sure that the proper evo version is installed (1.16 for me).

Thanks!
